logging:
  config: classpath:logs/logback-dev.xml

spring:
  datasource:
    hikari:
      master:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: y10h
        password: y10h_password
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-master
      slave:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: y10h
        password: y10h_password
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-slave

  redis:
    master:
      host: redis
      port: 6379
    password: root
    database: 12

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'false'
        show_sql: 'false'
        generate_statistics: 'false'
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: true

