# ===============================
# 로깅 설정
# ===============================
logging:
  config: classpath:logs/logback-local.xml

# ===============================
# 데이터베이스 설정 (H2)
# ===============================
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/lunch
    username: sa
    password:
    driver-class-name: org.h2.Driver
    console:
      enabled: true
      path: /h2-console

  # ===============================
  # JPA 및 Hibernate 설정
  # ===============================
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        show_sql: false
        use_sql_comments: false
        generate_statistics: false
        default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true # Hibernate SQL 출력
    defer-datasource-initialization: true
    open-in-view: true

  # ===============================
  # Redis 설정
  # ===============================
  redis:
    host: ENC(kcGli1hQDUI+PuWR5y3uGytjiSIacdjW4Ye8aZAFmZA+NU3j6phdPiNiI4LZOAgNkCz9wc197guDPE92gQe0lZQAM22HAXF3)
    port: 10352
    password: ENC(po92S3UxLb/hK+62OAX7vTdc0jvCl50G/GsoYAmumc0/YSU+3XB/3yIv99stu2S6)
    database: 0

# ===============================
# 프론트엔드 설정
# ===============================
front:
  url: http://localhost:3000