spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(AijAxgR0jt/dhY51aF+YOTeExTkn4nW2vj5hFjgkldG85jUwew+Mp+LO2405Gqvv2xiZxtCaNf/BLjx9vkVVfrS8I1g8QjIwRyrKqBEV5KYS2ksZpwrXsQ==)
            client-secret: ENC(Z00hTs1Yh3LogIH/zwyKdb4Axw0o8bd+QmHf3ttb9WnSiyVAliwcDcWR7DtbHzPl)
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

          naver:
            client-id: ENC(bNm2bOEeN5KJlFOapHm4NbmQNFHyCXwe3C/Wb6PVxsQ=)
            client-secret: ENC(iNfA1BjIvy+u5AtHgI8N0qdrCDKD6j4A)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

