logging:
  config: classpath:logs/logback-prod.xml

spring:
  datasource:
    hikari:
      master:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ENC(kd4oqenYj6DyNwa2iAF37g==)
        password: ENC(0MvOpfb4v9db+oaYGTLWwirc54gjyLFS)
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-master
      slave:
        jdbcUrl: jdbc:mysql://mysql:3306/yeoboya_lunch?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ENC(kd4oqenYj6DyNwa2iAF37g==)
        password: ENC(0MvOpfb4v9db+oaYGTLWwirc54gjyLFS)
        driverClassName: com.mysql.cj.jdbc.Driver
        poolName: kimzzang-db-slave

  redis:
    host: redis
    port: 6379
    password: ENC(0MvOpfb4v9db+oaYGTLWwirc54gjyLFS)
    database: 12

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'false'
        show_sql: 'false'
        generate_statistics: 'false'
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    open-in-view: true

